version: "2"
services:
  app:
    build: .
    links:
      - db
    ports:
      - "8080:8080"
    command: uwsgi --ini /app/uwsgi.ini
  db:
    image: mongo:3.4.9
    volumes_from:
      - db_data
    command: mongod --storageEngine wiredTiger
  db_data:
    image: busybox:latest
    volumes:
      - /data/db
